# Generated by Django 5.2.7 on 2025-11-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Ключ сессии')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Время первого визита')),
                ('last_action', models.DateTimeField(auto_now=True, verbose_name='Время последнего действия')),
            ],
        ),
    ]