# Generated by Django 5.2.7 on 2025-11-02 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0002_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomplan',
            options={'ordering': ['-upload_date'], 'verbose_name': 'План Помещения', 'verbose_name_plural': 'Планы Помещений'},
        ),
        migrations.RemoveField(
            model_name='roomplan',
            name='client',
        ),
        migrations.AddField(
            model_name='roomplan',
            name='plan_file',
            field=models.FileField(blank=True, null=True, upload_to='room_plans/', verbose_name='Файл плана'),
        ),
        migrations.AddField(
            model_name='roomplan',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='room_plans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='description',
            field=models.TextField(verbose_name='Описание помещения'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]