# Generated by Django 5.2.7 on 2025-11-02 09:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0003_alter_roomplan_options_remove_roomplan_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только кириллические буквы, пробелы и дефис', regex='^[А-Яа-яёЁ\\s\\-]+$')], verbose_name='ФИО')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.AlterModelOptions(
            name='roomplan',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='roomplan',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
        migrations.AddField(
            model_name='roomplan',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='Дизайн-проект'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='plan_file',
            field=models.ImageField(blank=True, help_text='Форматы: JPG, JPEG, PNG, BMP. Максимальный размер: 2MB', null=True, upload_to='room_plans/', verbose_name='Фото помещения или план'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'Принято в работу'), ('COMPLETED', 'Выполнено')], default='NEW', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название заявки'),
        ),
        migrations.AlterField(
            model_name='roomplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='roomplan',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='design_app.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]