# Generated by Django 5.2.7 on 2025-11-02 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0004_category_userprofile_delete_guest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='user',
        ),
        migrations.AddField(
            model_name='roomplan',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Назначена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('DESIGNER', 'Дизайнер'), ('MANAGER', 'Менеджер'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=10, verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='AuthorizedUser',
        ),
    ]