# Generated by Django 5.2.8 on 2025-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_app', '0005_remove_authorizeduser_user_roomplan_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('MANAGER', 'Менеджер'), ('ADMIN', 'Администратор')], default='CLIENT', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
